version: 1.0.{build}
skip_non_tags: false
image: Visual Studio 2019
build_script:
- ps: .\build.ps1
branches:
  only: 
  - master
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: oHxOGeZSmHySeSux4ih+8JaHgnOJd7fsSC2RP0BEgyv16e4z6jDV+kj+7W0nO2jT
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - scott@odetocode.com
  subject: UseNodeModules Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false