version: 1.0.{build}
skip_non_tags: true
build_script:
- ps: .\build.ps1
test: off
deploy:
- provider: NuGet
  api_key:
    secure: tg20msJwxYqlk0EwjZ1MuPXsX+ORK/7fxdeopd1aSnPaJX+gq9srs7i7VINiYTWS
  skip_symbols: true
notifications:
- provider: Email
  to:
  - scott@odetocode.com
  subject: UseNodeModules Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false